id: I03A6CF6D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T09:14:03+00:00'
last_modified: '2022-06-08T09:40:33.285876+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W26372
  title: 'དུང་དཀར་ཚིག་མཛོད་ཆེན་མོ།

    '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    BB0F:
      image_group_id: I1KG10856
      title: Volume 1 of bod rig pa'i tshig mdzod chen mo shes bya rab gsal
      total_pages: 2583
      order: 1
      base_file: BB0F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
