id: P006973
initial_creation_type: ocr
source_metadata:
  id: bdr:W26372
  title: 'དུང་དཀར་ཚིག་མཛོད་ཆེན་མོ།

    '
  author: ''
  volumes:
    6731ab98ba1a45a397a3610a15655b46:
      image_group_id: I1KG10856
      title: ''
      volume_number: 1
      total_pages: 2583
ebook_metadata:
  title: 'དུང་དཀར་ཚིག་མཛོད་ཆེན་མོ།

    '
  author: ''
  sku: P006973
  cover: cover.jpg
  layers:
  - pagination
