id: P006973
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W26372
  title: 'དུང་དཀར་ཚིག་མཛོད་ཆེན་མོ།

    '
  author: ''
  volumes:
    1104c05d62b34b14996ddc2b8ee8e155:
      image_group_id: I1KG10856
      title: Volume 1 of bod rig pa'i tshig mdzod chen mo shes bya rab gsal
      volume_number: 1
      total_pages: 2583
      base_file: v001.txt
